### ISSUE TITLE
[Feature request] Implement GLEM as an option for LM, GNN co-training

### ISSUE THREAD

**Issue by wangz10** [awslabs/graphstorm#241]
Authors' implementation can be found here: https://github.com/AndyJZhao/GLEM
```[tasklist]
### Tasks
- [ ] Support freezing GNN encoder and decoder
- [ ] https://github.com/awslabs/graphstorm/issues/252
- [ ] Support inference
- [ ] Support configuration of EM training by number of steps
- [ ] https://github.com/awslabs/graphstorm/issues/283
```

**Comment by wangz10** [comment]
@classicsong I saw this line in the code https://github.com/awslabs/graphstorm/blob/fc8b8dd4bb818968ff1f50d3c6b78cc0bed8d109/python/graphstorm/trainer/np_trainer.py#LL103C23-L103C23

"# TODO(xiangsx) Support freezing gnn encoder and decoder"

This is required for GLEM implementation. Are you working on this? Do you have an ETA for this feature?
