### ISSUE TITLE
[Roadmap] V0.2 Release Plan

### ISSUE THREAD

**Issue by classicsong** [awslabs/graphstorm#296]
The V0.2 release will focus on optimizing user experiences on graph construction and model training/inference, optimizing system efficiency and providing more GML models. 

- [Improvement] Optimizing user experiences on graph construction
  - [x] #294 
  - [x] #264 
  - [x] #259 
- [Improvement] Improving user interface and usability
  - [x] #265 
  - [x] Using logging to avoid many unnecessary messages
  - [x] #250 
  - [x] #43 
  - [x] #298 
  - [x] #301 
  - [x] #134 
  - [x] #350 
- [New Feature] Providing more sophisticated GML models.
  - [x] #295
  - [x] #364 
  - [x] #262 
  - [x] GNN-Bert distillation
- [Improvement] Optimizing training/inference efficiency
  - [x] #87 
  - [x] Integrate NVidia WholeGraph with GraphStorm for efficient feature fetching
- [Improvement] Optimizing model training
  - [x] #289 
  - [x] #365  
  - [x] #233 
- [Improvement] Documentation
  - [x] API doc
```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```
