### ISSUE TITLE
[Roadmap] 0.2.2 Release Plan. 

### ISSUE THREAD

**Issue by classicsong** [awslabs/graphstorm#702]
The V0.2.2 release will continuously focus on optimizing the new features released in V0.2, including distributed graph data processing, wholegraph support, Bert-distillation. It will also includes other improvements and features.

- [Improvement] Distributed graph data processing
  - [x] [GSProcessing] Huggingface Bert transformation support
  - [x] [GSProcessing] Huggingface Text Tokenization transformation support
  - [x] [GSProcessing/GConstruct] Align the ID mapping implementation between GConstruct and GSProcessing (#641 )
- [Improvement] WholeGraph Support
  - [x] [WholeGraph] Learnable embeddings on WholeGraph
  - [x] [WholeGraph] Intermediate embeddings on WholeGraph
- [New feature] Homogeneous graph native support
  - [x] #683 
- [New feature] Hard negative support
  - [x] #678 
- [New Example]
  - [x] GNN-Peft #701

Targeting release date: Feb 23rd.
