### ISSUE TITLE
[Roadmap] 0.3 Release Plan. 

### ISSUE THREAD

**Issue by classicsong** [awslabs/graphstorm#788]
The V0.3 release will focus on optimizing the code structure and adding new features such as multi-task learning. It will also includes other improvements and features.

- [Improvement] Graph data processing
  - [x] [GSProcessing] Optimize spark data processing user experience
  - [x] [GSProcessing] Support customize training/validation/test set #761 
  - [x] [Gconstruct] Support customize training/validation/test set for edge tasks (link prediction and edge prediction) #761 
- [Improvement] Modeling and benchmarks
  - [x] GPEFT example supports link prediction tasks
  - [x] Add GATv2 model for homogeneous graphs
  - [x] Add GraphStorm benchmarks using MAG and Amazon Review dataset.
 - [New Feature] Multi-task support
   - [x] #789  
 - [Improvement] Optimize GraphStorm code structure
   - [x] #754 
   - [x] #755 
   - [x] #756 
   - [x] #757 
- [Documentation] Update GraphStorm Doc
  - [x] #604 
  - [x] #830 
  - [x] #846 
  - [x] #844

**Comment by classicsong** [comment]
Decide to push #603 to the next release focusing on optimizing documentation.
