### ISSUE TITLE
[Roadmap] 0.3.1 Release Plan

### ISSUE THREAD

**Issue by classicsong** [awslabs/graphstorm#892]
The V0.3 release will focus on optimizing the document of GraphStorm. It will also includes other improvements and features.

- [Improvement] GraphStorm Documentation
  - [x] Update document of GSProcessing
  - [x] Introduction of Negative sampling for link prediction
  - [x] API Tutorial for custom model
  - [x] Reorganize the current document
  - [x] Update document of feature transformation
- [Improvement] New features
  - [x] Hit@K for link prediction evaluation
  - [ ] RotatE as link prediction decoder function
