### ISSUE TITLE
[GSProcessing] Support loading existing feature transform rules for floating point features.

### ISSUE THREAD

**Issue by classicsong** [awslabs/graphstorm#985]
We should support loading existing feature transform rules for floating point features in GSProcessing.

```[tasklist]
### Tasks
- [ ] Add save and replay for single "numerical"
- [ ] Add save and replay for single "multi-numerical"
- [ ] Add save and replay for single "bucket-numerical"
- [ ] Add save and replay for single "multi-categorical"
```
